apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: crossplane
  version: 1.17.0
  repo: https://charts.crossplane.io/stable
  releaseName: crossplane
  includeCRDs: true
  valuesFile: base-install.yaml

resources:
- provider-gcp-cloudplatform
- function-patch-and-transform.yaml
- function-go-templating.yaml
- function-auto-ready.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"