apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:  
- source: 
    kind: ConfigMap
    name: crossplane-env-vars
    fieldPath: data.PROJECT_ID
  targets: 
  - select:
      kind: ProviderConfig
      name: default
    fieldPaths:
    - spec.projectID

- source: 
    kind: ConfigMap
    name: crossplane-env-vars
    fieldPath: data.GCP_SA_DNS
  targets: 
  - select:
      kind: ControllerConfig
    fieldPaths:
    - metadata.annotations.[iam.gke.io/gcp-service-account]
    options:
      delimiter: "@"
      index: 1

- source: 
    kind: ConfigMap
    name: crossplane-env-vars
    fieldPath: data.GCP_CLOUDPLATFORM_SA
  targets: 
  - select:
      kind: ControllerConfig
      name: provider-gcp-cloudplatform      
    fieldPaths:
    - metadata.annotations.[iam.gke.io/gcp-service-account]
    options:
      delimiter: "@"
      index: 0

- source: 
    kind: ConfigMap
    name: crossplane-env-vars
    fieldPath: data.DEPLOY_ENV
  targets: 
  - select:
      name: provider-cloudflare-secret
      kind: Secret
    fieldPaths:
    - metadata.annotations.[avp.kubernetes.io/path]
    options:
      delimiter: "/"
      index: 0